// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(mls_ffiFFI)
import mls_ffiFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_mls_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_mls_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureMlsFfiInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




/**
 * One identity + one conversation, owned by Swift as an `Arc<MlsClient>`.
 */
public protocol MlsClientProtocol: AnyObject, Sendable {
    
    /**
     * Durably processed, so safe to acknowledge to the server.
     */
    func ackEligible() throws  -> [UInt64]
    
    /**
     * The grown group is durable before returning.
     */
    func addMember(keyPackage: Data) throws  -> AddOutcome
    
    /**
     * Returns a **wrapped** `commit` (for existing members via [`Self::process_self_inbound`],
     * which unwraps) plus the **raw** `welcome` (for the new device via [`Self::join_self_group`],
     * which does not).
     */
    func addSelfDevice(keyPackage: Data) throws  -> AddOutcome
    
    /**
     * **Atomic + fail-closed:** the transition + deadlines are committed before this returns `Ok`;
     * an invalid transition (double tap, replay) or failed write returns `Err` and reveals nothing.
     * `now_ms` is the caller's monotonic clock.
     */
    func beginSecretReveal(secretId: Data, nowMs: UInt64) throws 
    
    /**
     * Server rejected, or we're rebasing. State unchanged.
     */
    func clearStaged() throws 
    
    /**
     * Erase this device's visible message log when the user deletes the conversation. Protocol
     * state (ratchet, replay watermark, outbox, secret records) is retained, so later messages
     * still decrypt and a replayed secret still cannot be re-revealed. Local only — nothing is
     * sent, and the peer's copy is untouched.
     */
    func clearVisibleHistory() throws 
    
    /**
     * Idempotent. Durable state on disk is untouched — reopen with `open`.
     */
    func close() 
    
    func confirmAcked(ids: [UInt64]) throws 
    
    /**
     * Used on a detected screenshot/capture or overlay close. Idempotent; scrubs the body.
     */
    func consumeSecret(secretId: Data) throws 
    
    /**
     * `WrongState` if one already exists.
     */
    func createSelfGroup() throws 
    
    /**
     * Produces the versioned opaque envelope (`app-envelope v1`). **Idempotent:** a retry returns
     * the same bytes and never advances the ratchet again — no double-spend of a message key.
     */
    func encrypt(localId: UInt64) throws  -> Data
    
    /**
     * Durable draft; does NOT advance the ratchet.
     */
    func enqueue(plaintext: Data) throws  -> UInt64
    
    /**
     * ADR-0014 Slice 2c: share `K_r` (exactly 32 bytes) over the E2EE channel — the relay never
     * sees it. `encrypt`/`mark_sent` then proceed as for a normal message.
     */
    func enqueueDeliveryKeyGrant(keyR: Data) throws  -> UInt64
    
    /**
     * #7: replicate `entries` over the self-group. `WrongState` if none is established.
     */
    func enqueueHistorySync(entries: [HistoryEntry]) throws  -> UInt64
    
    /**
     * The classification + body are encrypted inside the content envelope, so the relay never
     * learns it is secret. `encrypt`/`mark_sent` then proceed exactly as for a normal message.
     */
    func enqueueSecret(body: Data) throws  -> SecretHandle
    
    func epoch() throws  -> UInt64
    
    func hasSelfGroup() throws  -> Bool
    
    /**
     * Up to `max` recent non-secret messages, for replication to a newly-linked device (#7).
     */
    func historyEntries(max: UInt32) throws  -> [HistoryEntry]
    
    /**
     * `Pending` → `Active`, persisted. On a bad Welcome the client stays `Pending` (retryable).
     */
    func joinGroup(welcome: Data) throws 
    
    /**
     * `WrongState` if a self-group is already established here.
     */
    func joinSelfGroup(welcome: Data) throws 
    
    /**
     * A one-time prekey to publish so others can add this client.
     */
    func keyPackage() throws  -> Data
    
    func markSent(localId: UInt64) throws 
    
    /**
     * Server accepted: advance the epoch and persist.
     */
    func mergeStaged() throws 
    
    /**
     * Cheap: no payload crosses the boundary.
     */
    func messageCount() throws  -> UInt64
    
    /**
     * Marshals the ENTIRE history across the boundary — fine for tests; a UI should use
     * [`Self::messages_page`] + [`Self::message_count`] instead.
     */
    func messages() throws  -> [StoredMessage]
    
    /**
     * Bounded window, oldest first. `limit` is clamped to [`MAX_PAGE_MESSAGES`] so one call can
     * never marshal an unbounded payload; an offset past the end returns an empty page.
     */
    func messagesPage(offset: UInt64, limit: UInt32) throws  -> [StoredMessage]
    
    /**
     * ADR-0010 recipient path: merges ONLY if the commit's actual effect equals the sender's signed
     * manifest (`next_epoch`/`added`/`removed` come from it). On mismatch: discarded unmerged,
     * `InvalidMessage`, state unchanged.
     */
    func processCommit(envelope: Data, nextEpoch: UInt64, added: [Data], removed: [Data]) throws 
    
    /**
     * All effects — advanced ratchet, stored message, dedup marker, ack-eligibility — are durable
     * together before returning.
     */
    func processInbound(envelopeId: UInt64, ciphertext: Data) throws  -> InboundResult
    
    /**
     * Self-group channel (ADR-0015 option 3): a `SecretConsumed` from another of this account's
     * devices, or a self-group membership commit. Decrypting with the self-group keeps the read
     * signal private to the account. Same dedup + ack contract as [`Self::process_inbound`].
     */
    func processSelfInbound(envelopeId: UInt64, ciphertext: Data) throws  -> InboundResult
    
    /**
     * Used when that device is revoked. The returned remove-commit advances the epoch, so the
     * removed device can no longer decrypt self-group traffic.
     */
    func removeSelfDevice(identity: Data) throws  -> Data
    
    /**
     * The consumption control message for a secret this device revealed (ADR-0015). `None` if the
     * secret is unknown, the sender's own, or unrevealed here. Encrypted with the self-group when
     * one exists (option 3 — the sender never learns of the open; recipients apply via
     * [`Self::process_self_inbound`]), else the conversation (option 2). Idempotent: repeated calls
     * return the same envelope and never double-advance the ratchet.
     */
    func secretConsumptionEnvelope(secretId: Data) throws  -> Data?
    
    /**
     * The current reveal phase of a secret at `now_ms` (advancing + persisting a state change).
     */
    func secretPhase(secretId: Data, nowMs: UInt64) throws  -> SecretPhase
    
    /**
     * Both 0 outside that phase. Drives the UI timer + fade.
     */
    func secretRemaining(secretId: Data, nowMs: UInt64) throws  -> SecretRemaining
    
    /**
     * The plaintext gate: `None` while sealed/counting down and forever after expiry (which also
     * scrubs + persists).
     */
    func secretVisibleBody(secretId: Data, nowMs: UInt64) throws  -> Data?
    
    /**
     * ADR-0010: builds commit + welcome WITHOUT advancing the group. Sign a manifest, POST
     * `/commit`, then [`merge_staged`](Self::merge_staged) on success or
     * [`clear_staged`](Self::clear_staged) on rejection. Never merge before the server's epoch CAS
     * confirms — that is how a race loser desyncs.
     */
    func stageAdd(keyPackage: Data) throws  -> AddOutcome
    
    /**
     * Stage a remove (see [`stage_add`](Self::stage_add)). `identity` is the target member's
     * credential identity bytes. Returns the commit; the group is not advanced until merged.
     */
    func stageRemove(identity: Data) throws  -> Data
    
    /**
     * 0 = pre-versioning; a Pending client also reports 0.
     */
    func storageFormatVersion() throws  -> UInt32
    
}
/**
 * One identity + one conversation, owned by Swift as an `Arc<MlsClient>`.
 */
open class MlsClient: MlsClientProtocol, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_mls_ffi_fn_clone_mlsclient(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_mls_ffi_fn_free_mlsclient(pointer, $0) }
    }

    
    /**
     * This client becomes the group creator/first member. Persists before returning.
     */
public static func createGroup(identity: Data, dbPath: String, atRestKey: Data)throws  -> MlsClient  {
    return try  FfiConverterTypeMlsClient_lift(try rustCallWithError(FfiConverterTypeMlsClientError_lift) {
    uniffi_mls_ffi_fn_constructor_mlsclient_create_group(
        FfiConverterData.lower(identity),
        FfiConverterString.lower(dbPath),
        FfiConverterData.lower(atRestKey),$0
    )
})
}
    
    /**
     * Create a fresh identity that will JOIN an existing group. Call `key_package()` to publish a
     * prekey, then `join_group(welcome)` once added. The pending identity is not yet durable — if
     * the process dies before joining, request a fresh key package.
     */
public static func newJoiner(identity: Data, dbPath: String, atRestKey: Data)throws  -> MlsClient  {
    return try  FfiConverterTypeMlsClient_lift(try rustCallWithError(FfiConverterTypeMlsClientError_lift) {
    uniffi_mls_ffi_fn_constructor_mlsclient_new_joiner(
        FfiConverterData.lower(identity),
        FfiConverterString.lower(dbPath),
        FfiConverterData.lower(atRestKey),$0
    )
})
}
    
    /**
     * Reopen the last durably-committed session (relaunch / crash recovery).
     */
public static func `open`(dbPath: String, atRestKey: Data)throws  -> MlsClient  {
    return try  FfiConverterTypeMlsClient_lift(try rustCallWithError(FfiConverterTypeMlsClientError_lift) {
    uniffi_mls_ffi_fn_constructor_mlsclient_open(
        FfiConverterString.lower(dbPath),
        FfiConverterData.lower(atRestKey),$0
    )
})
}
    

    
    /**
     * Durably processed, so safe to acknowledge to the server.
     */
open func ackEligible()throws  -> [UInt64]  {
    return try  FfiConverterSequenceUInt64.lift(try rustCallWithError(FfiConverterTypeMlsClientError_lift) {
    uniffi_mls_ffi_fn_method_mlsclient_ack_eligible(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * The grown group is durable before returning.
     */
open func addMember(keyPackage: Data)throws  -> AddOutcome  {
    return try  FfiConverterTypeAddOutcome_lift(try rustCallWithError(FfiConverterTypeMlsClientError_lift) {
    uniffi_mls_ffi_fn_method_mlsclient_add_member(self.uniffiClonePointer(),
        FfiConverterData.lower(keyPackage),$0
    )
})
}
    
    /**
     * Returns a **wrapped** `commit` (for existing members via [`Self::process_self_inbound`],
     * which unwraps) plus the **raw** `welcome` (for the new device via [`Self::join_self_group`],
     * which does not).
     */
open func addSelfDevice(keyPackage: Data)throws  -> AddOutcome  {
    return try  FfiConverterTypeAddOutcome_lift(try rustCallWithError(FfiConverterTypeMlsClientError_lift) {
    uniffi_mls_ffi_fn_method_mlsclient_add_self_device(self.uniffiClonePointer(),
        FfiConverterData.lower(keyPackage),$0
    )
})
}
    
    /**
     * **Atomic + fail-closed:** the transition + deadlines are committed before this returns `Ok`;
     * an invalid transition (double tap, replay) or failed write returns `Err` and reveals nothing.
     * `now_ms` is the caller's monotonic clock.
     */
open func beginSecretReveal(secretId: Data, nowMs: UInt64)throws   {try rustCallWithError(FfiConverterTypeMlsClientError_lift) {
    uniffi_mls_ffi_fn_method_mlsclient_begin_secret_reveal(self.uniffiClonePointer(),
        FfiConverterData.lower(secretId),
        FfiConverterUInt64.lower(nowMs),$0
    )
}
}
    
    /**
     * Server rejected, or we're rebasing. State unchanged.
     */
open func clearStaged()throws   {try rustCallWithError(FfiConverterTypeMlsClientError_lift) {
    uniffi_mls_ffi_fn_method_mlsclient_clear_staged(self.uniffiClonePointer(),$0
    )
}
}
    
    /**
     * Erase this device's visible message log when the user deletes the conversation. Protocol
     * state (ratchet, replay watermark, outbox, secret records) is retained, so later messages
     * still decrypt and a replayed secret still cannot be re-revealed. Local only — nothing is
     * sent, and the peer's copy is untouched.
     */
open func clearVisibleHistory()throws   {try rustCallWithError(FfiConverterTypeMlsClientError_lift) {
    uniffi_mls_ffi_fn_method_mlsclient_clear_visible_history(self.uniffiClonePointer(),$0
    )
}
}
    
    /**
     * Idempotent. Durable state on disk is untouched — reopen with `open`.
     */
open func close()  {try! rustCall() {
    uniffi_mls_ffi_fn_method_mlsclient_close(self.uniffiClonePointer(),$0
    )
}
}
    
open func confirmAcked(ids: [UInt64])throws   {try rustCallWithError(FfiConverterTypeMlsClientError_lift) {
    uniffi_mls_ffi_fn_method_mlsclient_confirm_acked(self.uniffiClonePointer(),
        FfiConverterSequenceUInt64.lower(ids),$0
    )
}
}
    
    /**
     * Used on a detected screenshot/capture or overlay close. Idempotent; scrubs the body.
     */
open func consumeSecret(secretId: Data)throws   {try rustCallWithError(FfiConverterTypeMlsClientError_lift) {
    uniffi_mls_ffi_fn_method_mlsclient_consume_secret(self.uniffiClonePointer(),
        FfiConverterData.lower(secretId),$0
    )
}
}
    
    /**
     * `WrongState` if one already exists.
     */
open func createSelfGroup()throws   {try rustCallWithError(FfiConverterTypeMlsClientError_lift) {
    uniffi_mls_ffi_fn_method_mlsclient_create_self_group(self.uniffiClonePointer(),$0
    )
}
}
    
    /**
     * Produces the versioned opaque envelope (`app-envelope v1`). **Idempotent:** a retry returns
     * the same bytes and never advances the ratchet again — no double-spend of a message key.
     */
open func encrypt(localId: UInt64)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeMlsClientError_lift) {
    uniffi_mls_ffi_fn_method_mlsclient_encrypt(self.uniffiClonePointer(),
        FfiConverterUInt64.lower(localId),$0
    )
})
}
    
    /**
     * Durable draft; does NOT advance the ratchet.
     */
open func enqueue(plaintext: Data)throws  -> UInt64  {
    return try  FfiConverterUInt64.lift(try rustCallWithError(FfiConverterTypeMlsClientError_lift) {
    uniffi_mls_ffi_fn_method_mlsclient_enqueue(self.uniffiClonePointer(),
        FfiConverterData.lower(plaintext),$0
    )
})
}
    
    /**
     * ADR-0014 Slice 2c: share `K_r` (exactly 32 bytes) over the E2EE channel — the relay never
     * sees it. `encrypt`/`mark_sent` then proceed as for a normal message.
     */
open func enqueueDeliveryKeyGrant(keyR: Data)throws  -> UInt64  {
    return try  FfiConverterUInt64.lift(try rustCallWithError(FfiConverterTypeMlsClientError_lift) {
    uniffi_mls_ffi_fn_method_mlsclient_enqueue_delivery_key_grant(self.uniffiClonePointer(),
        FfiConverterData.lower(keyR),$0
    )
})
}
    
    /**
     * #7: replicate `entries` over the self-group. `WrongState` if none is established.
     */
open func enqueueHistorySync(entries: [HistoryEntry])throws  -> UInt64  {
    return try  FfiConverterUInt64.lift(try rustCallWithError(FfiConverterTypeMlsClientError_lift) {
    uniffi_mls_ffi_fn_method_mlsclient_enqueue_history_sync(self.uniffiClonePointer(),
        FfiConverterSequenceTypeHistoryEntry.lower(entries),$0
    )
})
}
    
    /**
     * The classification + body are encrypted inside the content envelope, so the relay never
     * learns it is secret. `encrypt`/`mark_sent` then proceed exactly as for a normal message.
     */
open func enqueueSecret(body: Data)throws  -> SecretHandle  {
    return try  FfiConverterTypeSecretHandle_lift(try rustCallWithError(FfiConverterTypeMlsClientError_lift) {
    uniffi_mls_ffi_fn_method_mlsclient_enqueue_secret(self.uniffiClonePointer(),
        FfiConverterData.lower(body),$0
    )
})
}
    
open func epoch()throws  -> UInt64  {
    return try  FfiConverterUInt64.lift(try rustCallWithError(FfiConverterTypeMlsClientError_lift) {
    uniffi_mls_ffi_fn_method_mlsclient_epoch(self.uniffiClonePointer(),$0
    )
})
}
    
open func hasSelfGroup()throws  -> Bool  {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeMlsClientError_lift) {
    uniffi_mls_ffi_fn_method_mlsclient_has_self_group(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Up to `max` recent non-secret messages, for replication to a newly-linked device (#7).
     */
open func historyEntries(max: UInt32)throws  -> [HistoryEntry]  {
    return try  FfiConverterSequenceTypeHistoryEntry.lift(try rustCallWithError(FfiConverterTypeMlsClientError_lift) {
    uniffi_mls_ffi_fn_method_mlsclient_history_entries(self.uniffiClonePointer(),
        FfiConverterUInt32.lower(max),$0
    )
})
}
    
    /**
     * `Pending` → `Active`, persisted. On a bad Welcome the client stays `Pending` (retryable).
     */
open func joinGroup(welcome: Data)throws   {try rustCallWithError(FfiConverterTypeMlsClientError_lift) {
    uniffi_mls_ffi_fn_method_mlsclient_join_group(self.uniffiClonePointer(),
        FfiConverterData.lower(welcome),$0
    )
}
}
    
    /**
     * `WrongState` if a self-group is already established here.
     */
open func joinSelfGroup(welcome: Data)throws   {try rustCallWithError(FfiConverterTypeMlsClientError_lift) {
    uniffi_mls_ffi_fn_method_mlsclient_join_self_group(self.uniffiClonePointer(),
        FfiConverterData.lower(welcome),$0
    )
}
}
    
    /**
     * A one-time prekey to publish so others can add this client.
     */
open func keyPackage()throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeMlsClientError_lift) {
    uniffi_mls_ffi_fn_method_mlsclient_key_package(self.uniffiClonePointer(),$0
    )
})
}
    
open func markSent(localId: UInt64)throws   {try rustCallWithError(FfiConverterTypeMlsClientError_lift) {
    uniffi_mls_ffi_fn_method_mlsclient_mark_sent(self.uniffiClonePointer(),
        FfiConverterUInt64.lower(localId),$0
    )
}
}
    
    /**
     * Server accepted: advance the epoch and persist.
     */
open func mergeStaged()throws   {try rustCallWithError(FfiConverterTypeMlsClientError_lift) {
    uniffi_mls_ffi_fn_method_mlsclient_merge_staged(self.uniffiClonePointer(),$0
    )
}
}
    
    /**
     * Cheap: no payload crosses the boundary.
     */
open func messageCount()throws  -> UInt64  {
    return try  FfiConverterUInt64.lift(try rustCallWithError(FfiConverterTypeMlsClientError_lift) {
    uniffi_mls_ffi_fn_method_mlsclient_message_count(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Marshals the ENTIRE history across the boundary — fine for tests; a UI should use
     * [`Self::messages_page`] + [`Self::message_count`] instead.
     */
open func messages()throws  -> [StoredMessage]  {
    return try  FfiConverterSequenceTypeStoredMessage.lift(try rustCallWithError(FfiConverterTypeMlsClientError_lift) {
    uniffi_mls_ffi_fn_method_mlsclient_messages(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Bounded window, oldest first. `limit` is clamped to [`MAX_PAGE_MESSAGES`] so one call can
     * never marshal an unbounded payload; an offset past the end returns an empty page.
     */
open func messagesPage(offset: UInt64, limit: UInt32)throws  -> [StoredMessage]  {
    return try  FfiConverterSequenceTypeStoredMessage.lift(try rustCallWithError(FfiConverterTypeMlsClientError_lift) {
    uniffi_mls_ffi_fn_method_mlsclient_messages_page(self.uniffiClonePointer(),
        FfiConverterUInt64.lower(offset),
        FfiConverterUInt32.lower(limit),$0
    )
})
}
    
    /**
     * ADR-0010 recipient path: merges ONLY if the commit's actual effect equals the sender's signed
     * manifest (`next_epoch`/`added`/`removed` come from it). On mismatch: discarded unmerged,
     * `InvalidMessage`, state unchanged.
     */
open func processCommit(envelope: Data, nextEpoch: UInt64, added: [Data], removed: [Data])throws   {try rustCallWithError(FfiConverterTypeMlsClientError_lift) {
    uniffi_mls_ffi_fn_method_mlsclient_process_commit(self.uniffiClonePointer(),
        FfiConverterData.lower(envelope),
        FfiConverterUInt64.lower(nextEpoch),
        FfiConverterSequenceData.lower(added),
        FfiConverterSequenceData.lower(removed),$0
    )
}
}
    
    /**
     * All effects — advanced ratchet, stored message, dedup marker, ack-eligibility — are durable
     * together before returning.
     */
open func processInbound(envelopeId: UInt64, ciphertext: Data)throws  -> InboundResult  {
    return try  FfiConverterTypeInboundResult_lift(try rustCallWithError(FfiConverterTypeMlsClientError_lift) {
    uniffi_mls_ffi_fn_method_mlsclient_process_inbound(self.uniffiClonePointer(),
        FfiConverterUInt64.lower(envelopeId),
        FfiConverterData.lower(ciphertext),$0
    )
})
}
    
    /**
     * Self-group channel (ADR-0015 option 3): a `SecretConsumed` from another of this account's
     * devices, or a self-group membership commit. Decrypting with the self-group keeps the read
     * signal private to the account. Same dedup + ack contract as [`Self::process_inbound`].
     */
open func processSelfInbound(envelopeId: UInt64, ciphertext: Data)throws  -> InboundResult  {
    return try  FfiConverterTypeInboundResult_lift(try rustCallWithError(FfiConverterTypeMlsClientError_lift) {
    uniffi_mls_ffi_fn_method_mlsclient_process_self_inbound(self.uniffiClonePointer(),
        FfiConverterUInt64.lower(envelopeId),
        FfiConverterData.lower(ciphertext),$0
    )
})
}
    
    /**
     * Used when that device is revoked. The returned remove-commit advances the epoch, so the
     * removed device can no longer decrypt self-group traffic.
     */
open func removeSelfDevice(identity: Data)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeMlsClientError_lift) {
    uniffi_mls_ffi_fn_method_mlsclient_remove_self_device(self.uniffiClonePointer(),
        FfiConverterData.lower(identity),$0
    )
})
}
    
    /**
     * The consumption control message for a secret this device revealed (ADR-0015). `None` if the
     * secret is unknown, the sender's own, or unrevealed here. Encrypted with the self-group when
     * one exists (option 3 — the sender never learns of the open; recipients apply via
     * [`Self::process_self_inbound`]), else the conversation (option 2). Idempotent: repeated calls
     * return the same envelope and never double-advance the ratchet.
     */
open func secretConsumptionEnvelope(secretId: Data)throws  -> Data?  {
    return try  FfiConverterOptionData.lift(try rustCallWithError(FfiConverterTypeMlsClientError_lift) {
    uniffi_mls_ffi_fn_method_mlsclient_secret_consumption_envelope(self.uniffiClonePointer(),
        FfiConverterData.lower(secretId),$0
    )
})
}
    
    /**
     * The current reveal phase of a secret at `now_ms` (advancing + persisting a state change).
     */
open func secretPhase(secretId: Data, nowMs: UInt64)throws  -> SecretPhase  {
    return try  FfiConverterTypeSecretPhase_lift(try rustCallWithError(FfiConverterTypeMlsClientError_lift) {
    uniffi_mls_ffi_fn_method_mlsclient_secret_phase(self.uniffiClonePointer(),
        FfiConverterData.lower(secretId),
        FfiConverterUInt64.lower(nowMs),$0
    )
})
}
    
    /**
     * Both 0 outside that phase. Drives the UI timer + fade.
     */
open func secretRemaining(secretId: Data, nowMs: UInt64)throws  -> SecretRemaining  {
    return try  FfiConverterTypeSecretRemaining_lift(try rustCallWithError(FfiConverterTypeMlsClientError_lift) {
    uniffi_mls_ffi_fn_method_mlsclient_secret_remaining(self.uniffiClonePointer(),
        FfiConverterData.lower(secretId),
        FfiConverterUInt64.lower(nowMs),$0
    )
})
}
    
    /**
     * The plaintext gate: `None` while sealed/counting down and forever after expiry (which also
     * scrubs + persists).
     */
open func secretVisibleBody(secretId: Data, nowMs: UInt64)throws  -> Data?  {
    return try  FfiConverterOptionData.lift(try rustCallWithError(FfiConverterTypeMlsClientError_lift) {
    uniffi_mls_ffi_fn_method_mlsclient_secret_visible_body(self.uniffiClonePointer(),
        FfiConverterData.lower(secretId),
        FfiConverterUInt64.lower(nowMs),$0
    )
})
}
    
    /**
     * ADR-0010: builds commit + welcome WITHOUT advancing the group. Sign a manifest, POST
     * `/commit`, then [`merge_staged`](Self::merge_staged) on success or
     * [`clear_staged`](Self::clear_staged) on rejection. Never merge before the server's epoch CAS
     * confirms — that is how a race loser desyncs.
     */
open func stageAdd(keyPackage: Data)throws  -> AddOutcome  {
    return try  FfiConverterTypeAddOutcome_lift(try rustCallWithError(FfiConverterTypeMlsClientError_lift) {
    uniffi_mls_ffi_fn_method_mlsclient_stage_add(self.uniffiClonePointer(),
        FfiConverterData.lower(keyPackage),$0
    )
})
}
    
    /**
     * Stage a remove (see [`stage_add`](Self::stage_add)). `identity` is the target member's
     * credential identity bytes. Returns the commit; the group is not advanced until merged.
     */
open func stageRemove(identity: Data)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeMlsClientError_lift) {
    uniffi_mls_ffi_fn_method_mlsclient_stage_remove(self.uniffiClonePointer(),
        FfiConverterData.lower(identity),$0
    )
})
}
    
    /**
     * 0 = pre-versioning; a Pending client also reports 0.
     */
open func storageFormatVersion()throws  -> UInt32  {
    return try  FfiConverterUInt32.lift(try rustCallWithError(FfiConverterTypeMlsClientError_lift) {
    uniffi_mls_ffi_fn_method_mlsclient_storage_format_version(self.uniffiClonePointer(),$0
    )
})
}
    

}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMlsClient: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = MlsClient

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> MlsClient {
        return MlsClient(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: MlsClient) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MlsClient {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: MlsClient, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMlsClient_lift(_ pointer: UnsafeMutableRawPointer) throws -> MlsClient {
    return try FfiConverterTypeMlsClient.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMlsClient_lower(_ value: MlsClient) -> UnsafeMutableRawPointer {
    return FfiConverterTypeMlsClient.lower(value)
}




/**
 * Commit fans out to existing members; welcome goes to the new one. Both opaque.
 */
public struct AddOutcome {
    public var commit: Data
    public var welcome: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(commit: Data, welcome: Data) {
        self.commit = commit
        self.welcome = welcome
    }
}

#if compiler(>=6)
extension AddOutcome: Sendable {}
#endif


extension AddOutcome: Equatable, Hashable {
    public static func ==(lhs: AddOutcome, rhs: AddOutcome) -> Bool {
        if lhs.commit != rhs.commit {
            return false
        }
        if lhs.welcome != rhs.welcome {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(commit)
        hasher.combine(welcome)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAddOutcome: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AddOutcome {
        return
            try AddOutcome(
                commit: FfiConverterData.read(from: &buf), 
                welcome: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: AddOutcome, into buf: inout [UInt8]) {
        FfiConverterData.write(value.commit, into: &buf)
        FfiConverterData.write(value.welcome, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAddOutcome_lift(_ buf: RustBuffer) throws -> AddOutcome {
    return try FfiConverterTypeAddOutcome.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAddOutcome_lower(_ value: AddOutcome) -> RustBuffer {
    return FfiConverterTypeAddOutcome.lower(value)
}


/**
 * Lets Swift assert it links a compatible core and refuse on mismatch (ADR-0007).
 */
public struct Capabilities {
    public var bindingVersion: String
    public var coreVersion: String
    public var `protocol`: String
    public var ciphersuite: String
    public var storageFormatVersion: UInt32
    public var maxIdentity: UInt64
    public var maxKeyPackage: UInt64
    public var maxWelcome: UInt64
    public var maxEnvelope: UInt64
    public var maxPlaintext: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(bindingVersion: String, coreVersion: String, `protocol`: String, ciphersuite: String, storageFormatVersion: UInt32, maxIdentity: UInt64, maxKeyPackage: UInt64, maxWelcome: UInt64, maxEnvelope: UInt64, maxPlaintext: UInt64) {
        self.bindingVersion = bindingVersion
        self.coreVersion = coreVersion
        self.`protocol` = `protocol`
        self.ciphersuite = ciphersuite
        self.storageFormatVersion = storageFormatVersion
        self.maxIdentity = maxIdentity
        self.maxKeyPackage = maxKeyPackage
        self.maxWelcome = maxWelcome
        self.maxEnvelope = maxEnvelope
        self.maxPlaintext = maxPlaintext
    }
}

#if compiler(>=6)
extension Capabilities: Sendable {}
#endif


extension Capabilities: Equatable, Hashable {
    public static func ==(lhs: Capabilities, rhs: Capabilities) -> Bool {
        if lhs.bindingVersion != rhs.bindingVersion {
            return false
        }
        if lhs.coreVersion != rhs.coreVersion {
            return false
        }
        if lhs.`protocol` != rhs.`protocol` {
            return false
        }
        if lhs.ciphersuite != rhs.ciphersuite {
            return false
        }
        if lhs.storageFormatVersion != rhs.storageFormatVersion {
            return false
        }
        if lhs.maxIdentity != rhs.maxIdentity {
            return false
        }
        if lhs.maxKeyPackage != rhs.maxKeyPackage {
            return false
        }
        if lhs.maxWelcome != rhs.maxWelcome {
            return false
        }
        if lhs.maxEnvelope != rhs.maxEnvelope {
            return false
        }
        if lhs.maxPlaintext != rhs.maxPlaintext {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(bindingVersion)
        hasher.combine(coreVersion)
        hasher.combine(`protocol`)
        hasher.combine(ciphersuite)
        hasher.combine(storageFormatVersion)
        hasher.combine(maxIdentity)
        hasher.combine(maxKeyPackage)
        hasher.combine(maxWelcome)
        hasher.combine(maxEnvelope)
        hasher.combine(maxPlaintext)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCapabilities: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Capabilities {
        return
            try Capabilities(
                bindingVersion: FfiConverterString.read(from: &buf), 
                coreVersion: FfiConverterString.read(from: &buf), 
                protocol: FfiConverterString.read(from: &buf), 
                ciphersuite: FfiConverterString.read(from: &buf), 
                storageFormatVersion: FfiConverterUInt32.read(from: &buf), 
                maxIdentity: FfiConverterUInt64.read(from: &buf), 
                maxKeyPackage: FfiConverterUInt64.read(from: &buf), 
                maxWelcome: FfiConverterUInt64.read(from: &buf), 
                maxEnvelope: FfiConverterUInt64.read(from: &buf), 
                maxPlaintext: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: Capabilities, into buf: inout [UInt8]) {
        FfiConverterString.write(value.bindingVersion, into: &buf)
        FfiConverterString.write(value.coreVersion, into: &buf)
        FfiConverterString.write(value.`protocol`, into: &buf)
        FfiConverterString.write(value.ciphersuite, into: &buf)
        FfiConverterUInt32.write(value.storageFormatVersion, into: &buf)
        FfiConverterUInt64.write(value.maxIdentity, into: &buf)
        FfiConverterUInt64.write(value.maxKeyPackage, into: &buf)
        FfiConverterUInt64.write(value.maxWelcome, into: &buf)
        FfiConverterUInt64.write(value.maxEnvelope, into: &buf)
        FfiConverterUInt64.write(value.maxPlaintext, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCapabilities_lift(_ buf: RustBuffer) throws -> Capabilities {
    return try FfiConverterTypeCapabilities.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCapabilities_lower(_ value: Capabilities) -> RustBuffer {
    return FfiConverterTypeCapabilities.lower(value)
}


/**
 * One past message in a history-sync batch (#7). Secrets are never included.
 */
public struct HistoryEntry {
    public var outbound: Bool
    public var body: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(outbound: Bool, body: Data) {
        self.outbound = outbound
        self.body = body
    }
}

#if compiler(>=6)
extension HistoryEntry: Sendable {}
#endif


extension HistoryEntry: Equatable, Hashable {
    public static func ==(lhs: HistoryEntry, rhs: HistoryEntry) -> Bool {
        if lhs.outbound != rhs.outbound {
            return false
        }
        if lhs.body != rhs.body {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(outbound)
        hasher.combine(body)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHistoryEntry: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HistoryEntry {
        return
            try HistoryEntry(
                outbound: FfiConverterBool.read(from: &buf), 
                body: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: HistoryEntry, into buf: inout [UInt8]) {
        FfiConverterBool.write(value.outbound, into: &buf)
        FfiConverterData.write(value.body, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHistoryEntry_lift(_ buf: RustBuffer) throws -> HistoryEntry {
    return try FfiConverterTypeHistoryEntry.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHistoryEntry_lower(_ value: HistoryEntry) -> RustBuffer {
    return FfiConverterTypeHistoryEntry.lower(value)
}


public struct SecretHandle {
    public var localId: UInt64
    public var secretId: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(localId: UInt64, secretId: Data) {
        self.localId = localId
        self.secretId = secretId
    }
}

#if compiler(>=6)
extension SecretHandle: Sendable {}
#endif


extension SecretHandle: Equatable, Hashable {
    public static func ==(lhs: SecretHandle, rhs: SecretHandle) -> Bool {
        if lhs.localId != rhs.localId {
            return false
        }
        if lhs.secretId != rhs.secretId {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(localId)
        hasher.combine(secretId)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSecretHandle: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SecretHandle {
        return
            try SecretHandle(
                localId: FfiConverterUInt64.read(from: &buf), 
                secretId: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: SecretHandle, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.localId, into: &buf)
        FfiConverterData.write(value.secretId, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSecretHandle_lift(_ buf: RustBuffer) throws -> SecretHandle {
    return try FfiConverterTypeSecretHandle.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSecretHandle_lower(_ value: SecretHandle) -> RustBuffer {
    return FfiConverterTypeSecretHandle.lower(value)
}


/**
 * Both 0 outside that phase.
 */
public struct SecretRemaining {
    public var countdownMs: UInt64
    public var viewMs: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(countdownMs: UInt64, viewMs: UInt64) {
        self.countdownMs = countdownMs
        self.viewMs = viewMs
    }
}

#if compiler(>=6)
extension SecretRemaining: Sendable {}
#endif


extension SecretRemaining: Equatable, Hashable {
    public static func ==(lhs: SecretRemaining, rhs: SecretRemaining) -> Bool {
        if lhs.countdownMs != rhs.countdownMs {
            return false
        }
        if lhs.viewMs != rhs.viewMs {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(countdownMs)
        hasher.combine(viewMs)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSecretRemaining: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SecretRemaining {
        return
            try SecretRemaining(
                countdownMs: FfiConverterUInt64.read(from: &buf), 
                viewMs: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: SecretRemaining, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.countdownMs, into: &buf)
        FfiConverterUInt64.write(value.viewMs, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSecretRemaining_lift(_ buf: RustBuffer) throws -> SecretRemaining {
    return try FfiConverterTypeSecretRemaining.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSecretRemaining_lower(_ value: SecretRemaining) -> RustBuffer {
    return FfiConverterTypeSecretRemaining.lower(value)
}


/**
 * What the UI renders.
 */
public struct StoredMessage {
    public var localId: UInt64
    public var direction: Direction
    public var plaintext: Data
    public var envelopeId: UInt64?
    /**
     * `Some` (16 bytes) for a secret; `plaintext` is then empty — render a placeholder/tombstone
     * driven by [`MlsClient::secret_phase`], never the body.
     */
    public var secretId: Data?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(localId: UInt64, direction: Direction, plaintext: Data, envelopeId: UInt64?, 
        /**
         * `Some` (16 bytes) for a secret; `plaintext` is then empty — render a placeholder/tombstone
         * driven by [`MlsClient::secret_phase`], never the body.
         */secretId: Data?) {
        self.localId = localId
        self.direction = direction
        self.plaintext = plaintext
        self.envelopeId = envelopeId
        self.secretId = secretId
    }
}

#if compiler(>=6)
extension StoredMessage: Sendable {}
#endif


extension StoredMessage: Equatable, Hashable {
    public static func ==(lhs: StoredMessage, rhs: StoredMessage) -> Bool {
        if lhs.localId != rhs.localId {
            return false
        }
        if lhs.direction != rhs.direction {
            return false
        }
        if lhs.plaintext != rhs.plaintext {
            return false
        }
        if lhs.envelopeId != rhs.envelopeId {
            return false
        }
        if lhs.secretId != rhs.secretId {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(localId)
        hasher.combine(direction)
        hasher.combine(plaintext)
        hasher.combine(envelopeId)
        hasher.combine(secretId)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeStoredMessage: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> StoredMessage {
        return
            try StoredMessage(
                localId: FfiConverterUInt64.read(from: &buf), 
                direction: FfiConverterTypeDirection.read(from: &buf), 
                plaintext: FfiConverterData.read(from: &buf), 
                envelopeId: FfiConverterOptionUInt64.read(from: &buf), 
                secretId: FfiConverterOptionData.read(from: &buf)
        )
    }

    public static func write(_ value: StoredMessage, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.localId, into: &buf)
        FfiConverterTypeDirection.write(value.direction, into: &buf)
        FfiConverterData.write(value.plaintext, into: &buf)
        FfiConverterOptionUInt64.write(value.envelopeId, into: &buf)
        FfiConverterOptionData.write(value.secretId, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeStoredMessage_lift(_ buf: RustBuffer) throws -> StoredMessage {
    return try FfiConverterTypeStoredMessage.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeStoredMessage_lower(_ value: StoredMessage) -> RustBuffer {
    return FfiConverterTypeStoredMessage.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum Direction {
    
    case inbound
    case outbound
}


#if compiler(>=6)
extension Direction: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDirection: FfiConverterRustBuffer {
    typealias SwiftType = Direction

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Direction {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .inbound
        
        case 2: return .outbound
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: Direction, into buf: inout [UInt8]) {
        switch value {
        
        
        case .inbound:
            writeInt(&buf, Int32(1))
        
        
        case .outbound:
            writeInt(&buf, Int32(2))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDirection_lift(_ buf: RustBuffer) throws -> Direction {
    return try FfiConverterTypeDirection.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDirection_lower(_ value: Direction) -> RustBuffer {
    return FfiConverterTypeDirection.lower(value)
}


extension Direction: Equatable, Hashable {}






// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum InboundResult {
    
    case application(plaintext: Data
    )
    /**
     * A commit advanced group state; no user-visible content.
     */
    case stateAdvanced
    /**
     * At-least-once redelivery or a replayed secret id — a durable no-op.
     */
    case duplicate
    /**
     * Stored sealed; the body is NOT delivered here. Show a placeholder and reveal later via
     * [`MlsClient::begin_secret_reveal`].
     */
    case secretSealed(secretId: Data
    )
    /**
     * ADR-0015: another device revealed `secret_id`; this copy is consumed. Refresh any
     * placeholder to its tombstone.
     */
    case secretConsumedRemotely(secretId: Data
    )
    /**
     * ADR-0014 Slice 2c: store `K_r` keyed by the sender for future sealed sends.
     */
    case deliveryKeyGranted(keyR: Data
    )
    /**
     * #7: `count` past messages were appended to this device's log.
     */
    case historySynced(count: UInt64
    )
}


#if compiler(>=6)
extension InboundResult: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeInboundResult: FfiConverterRustBuffer {
    typealias SwiftType = InboundResult

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> InboundResult {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .application(plaintext: try FfiConverterData.read(from: &buf)
        )
        
        case 2: return .stateAdvanced
        
        case 3: return .duplicate
        
        case 4: return .secretSealed(secretId: try FfiConverterData.read(from: &buf)
        )
        
        case 5: return .secretConsumedRemotely(secretId: try FfiConverterData.read(from: &buf)
        )
        
        case 6: return .deliveryKeyGranted(keyR: try FfiConverterData.read(from: &buf)
        )
        
        case 7: return .historySynced(count: try FfiConverterUInt64.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: InboundResult, into buf: inout [UInt8]) {
        switch value {
        
        
        case let .application(plaintext):
            writeInt(&buf, Int32(1))
            FfiConverterData.write(plaintext, into: &buf)
            
        
        case .stateAdvanced:
            writeInt(&buf, Int32(2))
        
        
        case .duplicate:
            writeInt(&buf, Int32(3))
        
        
        case let .secretSealed(secretId):
            writeInt(&buf, Int32(4))
            FfiConverterData.write(secretId, into: &buf)
            
        
        case let .secretConsumedRemotely(secretId):
            writeInt(&buf, Int32(5))
            FfiConverterData.write(secretId, into: &buf)
            
        
        case let .deliveryKeyGranted(keyR):
            writeInt(&buf, Int32(6))
            FfiConverterData.write(keyR, into: &buf)
            
        
        case let .historySynced(count):
            writeInt(&buf, Int32(7))
            FfiConverterUInt64.write(count, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeInboundResult_lift(_ buf: RustBuffer) throws -> InboundResult {
    return try FfiConverterTypeInboundResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeInboundResult_lower(_ value: InboundResult) -> RustBuffer {
    return FfiConverterTypeInboundResult.lower(value)
}


extension InboundResult: Equatable, Hashable {}







/**
 * Messages are variant-only: no library internals, key bytes, plaintext, or paths ever appear
 * (asserted by a redaction test).
 */
public enum MlsClientError: Swift.Error {

    
    
    case InputTooLarge
    case BadKeyLength
    case WrongState
    case NotFound
    case InvalidMessage
    case NoSession
    case Journal
    case Closed
    case Internal
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMlsClientError: FfiConverterRustBuffer {
    typealias SwiftType = MlsClientError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MlsClientError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .InputTooLarge
        case 2: return .BadKeyLength
        case 3: return .WrongState
        case 4: return .NotFound
        case 5: return .InvalidMessage
        case 6: return .NoSession
        case 7: return .Journal
        case 8: return .Closed
        case 9: return .Internal

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: MlsClientError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case .InputTooLarge:
            writeInt(&buf, Int32(1))
        
        
        case .BadKeyLength:
            writeInt(&buf, Int32(2))
        
        
        case .WrongState:
            writeInt(&buf, Int32(3))
        
        
        case .NotFound:
            writeInt(&buf, Int32(4))
        
        
        case .InvalidMessage:
            writeInt(&buf, Int32(5))
        
        
        case .NoSession:
            writeInt(&buf, Int32(6))
        
        
        case .Journal:
            writeInt(&buf, Int32(7))
        
        
        case .Closed:
            writeInt(&buf, Int32(8))
        
        
        case .Internal:
            writeInt(&buf, Int32(9))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMlsClientError_lift(_ buf: RustBuffer) throws -> MlsClientError {
    return try FfiConverterTypeMlsClientError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMlsClientError_lower(_ value: MlsClientError) -> RustBuffer {
    return FfiConverterTypeMlsClientError.lower(value)
}


extension MlsClientError: Equatable, Hashable {}




extension MlsClientError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}




// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Mirrors `mls_core::secret::SecretState`.
 */

public enum SecretPhase {
    
    /**
     * Not tapped; no timer running.
     */
    case sealed
    case countdown
    case visible
    /**
     * Terminal: plaintext gone, cannot reopen.
     */
    case consumed
    /**
     * No secret with this id is known here.
     */
    case unknown
}


#if compiler(>=6)
extension SecretPhase: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSecretPhase: FfiConverterRustBuffer {
    typealias SwiftType = SecretPhase

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SecretPhase {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .sealed
        
        case 2: return .countdown
        
        case 3: return .visible
        
        case 4: return .consumed
        
        case 5: return .unknown
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: SecretPhase, into buf: inout [UInt8]) {
        switch value {
        
        
        case .sealed:
            writeInt(&buf, Int32(1))
        
        
        case .countdown:
            writeInt(&buf, Int32(2))
        
        
        case .visible:
            writeInt(&buf, Int32(3))
        
        
        case .consumed:
            writeInt(&buf, Int32(4))
        
        
        case .unknown:
            writeInt(&buf, Int32(5))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSecretPhase_lift(_ buf: RustBuffer) throws -> SecretPhase {
    return try FfiConverterTypeSecretPhase.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSecretPhase_lower(_ value: SecretPhase) -> RustBuffer {
    return FfiConverterTypeSecretPhase.lower(value)
}


extension SecretPhase: Equatable, Hashable {}






#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt64: FfiConverterRustBuffer {
    typealias SwiftType = UInt64?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt64.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt64.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionData: FfiConverterRustBuffer {
    typealias SwiftType = Data?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterData.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterData.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceUInt64: FfiConverterRustBuffer {
    typealias SwiftType = [UInt64]

    public static func write(_ value: [UInt64], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterUInt64.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [UInt64] {
        let len: Int32 = try readInt(&buf)
        var seq = [UInt64]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterUInt64.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceData: FfiConverterRustBuffer {
    typealias SwiftType = [Data]

    public static func write(_ value: [Data], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterData.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Data] {
        let len: Int32 = try readInt(&buf)
        var seq = [Data]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterData.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeHistoryEntry: FfiConverterRustBuffer {
    typealias SwiftType = [HistoryEntry]

    public static func write(_ value: [HistoryEntry], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeHistoryEntry.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [HistoryEntry] {
        let len: Int32 = try readInt(&buf)
        var seq = [HistoryEntry]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeHistoryEntry.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeStoredMessage: FfiConverterRustBuffer {
    typealias SwiftType = [StoredMessage]

    public static func write(_ value: [StoredMessage], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeStoredMessage.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [StoredMessage] {
        let len: Int32 = try readInt(&buf)
        var seq = [StoredMessage]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeStoredMessage.read(from: &buf))
        }
        return seq
    }
}
/**
 * For a quick human/log check.
 */
public func bindingVersion() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_mls_ffi_fn_func_binding_version($0
    )
})
}
/**
 * Machine-checkable (ADR-0007 version compatibility).
 */
public func capabilities() -> Capabilities  {
    return try!  FfiConverterTypeCapabilities_lift(try! rustCall() {
    uniffi_mls_ffi_fn_func_capabilities($0
    )
})
}
/**
 * Bundled system text — never an external resource that could fail at runtime.
 */
public func secretTombstoneText() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_mls_ffi_fn_func_secret_tombstone_text($0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 29
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_mls_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_mls_ffi_checksum_func_binding_version() != 64513) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_mls_ffi_checksum_func_capabilities() != 19744) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_mls_ffi_checksum_func_secret_tombstone_text() != 3901) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_mls_ffi_checksum_method_mlsclient_ack_eligible() != 21709) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_mls_ffi_checksum_method_mlsclient_add_member() != 27587) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_mls_ffi_checksum_method_mlsclient_add_self_device() != 1966) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_mls_ffi_checksum_method_mlsclient_begin_secret_reveal() != 13740) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_mls_ffi_checksum_method_mlsclient_clear_staged() != 11061) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_mls_ffi_checksum_method_mlsclient_clear_visible_history() != 41729) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_mls_ffi_checksum_method_mlsclient_close() != 6369) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_mls_ffi_checksum_method_mlsclient_confirm_acked() != 51522) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_mls_ffi_checksum_method_mlsclient_consume_secret() != 62728) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_mls_ffi_checksum_method_mlsclient_create_self_group() != 24532) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_mls_ffi_checksum_method_mlsclient_encrypt() != 56956) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_mls_ffi_checksum_method_mlsclient_enqueue() != 21140) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_mls_ffi_checksum_method_mlsclient_enqueue_delivery_key_grant() != 56582) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_mls_ffi_checksum_method_mlsclient_enqueue_history_sync() != 59844) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_mls_ffi_checksum_method_mlsclient_enqueue_secret() != 19913) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_mls_ffi_checksum_method_mlsclient_epoch() != 12252) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_mls_ffi_checksum_method_mlsclient_has_self_group() != 39595) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_mls_ffi_checksum_method_mlsclient_history_entries() != 5238) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_mls_ffi_checksum_method_mlsclient_join_group() != 20582) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_mls_ffi_checksum_method_mlsclient_join_self_group() != 51420) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_mls_ffi_checksum_method_mlsclient_key_package() != 41222) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_mls_ffi_checksum_method_mlsclient_mark_sent() != 42917) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_mls_ffi_checksum_method_mlsclient_merge_staged() != 17494) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_mls_ffi_checksum_method_mlsclient_message_count() != 39791) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_mls_ffi_checksum_method_mlsclient_messages() != 9968) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_mls_ffi_checksum_method_mlsclient_messages_page() != 36640) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_mls_ffi_checksum_method_mlsclient_process_commit() != 4908) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_mls_ffi_checksum_method_mlsclient_process_inbound() != 65073) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_mls_ffi_checksum_method_mlsclient_process_self_inbound() != 28883) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_mls_ffi_checksum_method_mlsclient_remove_self_device() != 4041) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_mls_ffi_checksum_method_mlsclient_secret_consumption_envelope() != 27555) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_mls_ffi_checksum_method_mlsclient_secret_phase() != 29195) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_mls_ffi_checksum_method_mlsclient_secret_remaining() != 64082) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_mls_ffi_checksum_method_mlsclient_secret_visible_body() != 8801) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_mls_ffi_checksum_method_mlsclient_stage_add() != 49236) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_mls_ffi_checksum_method_mlsclient_stage_remove() != 13093) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_mls_ffi_checksum_method_mlsclient_storage_format_version() != 65410) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_mls_ffi_checksum_constructor_mlsclient_create_group() != 42599) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_mls_ffi_checksum_constructor_mlsclient_new_joiner() != 33443) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_mls_ffi_checksum_constructor_mlsclient_open() != 33444) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureMlsFfiInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all