import CryptoKit
import XCTest
@testable import NedwonsKit

final class ClientTranscriptsTests: XCTestCase {
    private let fixedPublicKey = Data([0x04]) + Data((0 ..< 64).map { UInt8($0) })
    private let accountID = Data((0 ..< 16).map { UInt8($0 * 0x11) })
    private let deviceID = Data((1 ... 16).map { UInt8($0) })
    private let challenge = Data((0 ..< 32).map { UInt8($0) })
    private let txnID = Data((0xF0 ... 0xFF).map { UInt8($0) })

    /// The login builder produces the same bytes as encoding the shared sample input.
    func testLoginBuilderMatchesSampleVector() {
        let built = ClientTranscripts.login(
            accountID: accountID,
            deviceID: deviceID,
            publicKey: fixedPublicKey,
            challengeNonce: challenge,
            expiresAt: 1_000_000_000,
            txnID: txnID
        )
        let expected = AuthTranscript.encode(
            AuthTranscript.sampleLoginVectorInput(publicKey: fixedPublicKey)
        )
        XCTAssertEqual(built, expected)
    }

    /// Register and login differ only by the action byte (offset 26: 4-byte length +
    /// 20-byte domain + 2-byte version = 26).
    func testActionByteDiffersBetweenRegisterAndLogin() {
        let login = ClientTranscripts.login(
            accountID: accountID, deviceID: deviceID, publicKey: fixedPublicKey,
            challengeNonce: challenge, expiresAt: 1_000_000_000, txnID: txnID
        )
        let register = ClientTranscripts.register(
            accountID: accountID, deviceID: deviceID, publicKey: fixedPublicKey,
            challengeNonce: challenge, expiresAt: 1_000_000_000, txnID: txnID
        )
        XCTAssertNotEqual(login, register)
        // Action byte sits after len32(domain) + domain ("app.nedwons.auth.v1", 19 bytes) + version + protocol.
        XCTAssertEqual(login[25], AuthAction.login.rawValue)
        XCTAssertEqual(register[25], AuthAction.register.rawValue)
    }

    /// The refresh transaction id must byte-match the backend's `refresh_txn_id`
    /// (golden generated by `cargo run -p auth-core --example refresh_txn_vector`).
    func testRefreshTxnIDMatchesBackend() {
        let token = Data((0xA0 ... 0xBF).map { UInt8($0) }) // 32 bytes
        let tokenHash = Data(SHA256.hash(data: token))
        let txn = ClientTranscripts.refreshTxnID(fromTokenHash: tokenHash)
        XCTAssertEqual(Hex.encode(txn), "56b5c1c652890aa43744c0b55f192235")
    }
}
