#!/usr/bin/env bash
# Reproducible build of the mls-ffi Apple artifacts (ADR-0007 Phase 3).
#
# Produces, from a clean tree:
#   1. static libraries for macOS (host), iOS device, and iOS simulator (Apple Silicon);
#   2. the UniFFI Swift bindings, generated in *library mode* from the built host library so they
#      cannot drift from the exported surface;
#   3. an XCFramework bundling all three slices with a shared C module (`mls_ffiFFI`);
#   4. a manifest recording the archs + artifact SHA-256s (provenance / stale-detection).
#
# The generated Swift (`Sources/MlsFfi/mls_ffi.swift`) is committed as a build artifact; CI runs
# this script and fails if it is out of date (see --check). The XCFramework itself is a large
# derived binary and is NOT committed (.gitignore) — it is rebuilt here on demand.
#
# Requires: rustup with aarch64-apple-{darwin,ios,ios-sim} targets, Xcode (xcodebuild), Swift 6.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
FFI="$ROOT/core/mls-ffi"
PKG="$ROOT/apps/ios/SentinelMLS"
BINDINGS_DIR="$PKG/Sources/MlsFfi"
XCF="$PKG/MlsFfi.xcframework"
STAGE="$FFI/target/apple-stage"

HOST="aarch64-apple-darwin"
IOS="aarch64-apple-ios"
SIM="aarch64-apple-ios-sim"
LIB="libmls_ffi"

# Deployment targets match SentinelKit/Package.swift (ADR-0007).
export MACOSX_DEPLOYMENT_TARGET="14.0"
export IPHONEOS_DEPLOYMENT_TARGET="17.0"

CHECK_ONLY="${1:-}"

echo "== [1/5] build static libs (release) =="
cd "$FFI"
export PATH="$HOME/.cargo/bin:$PATH"
# Host: full build (also yields the cdylib the bindgen introspects, and the bindgen bin).
cargo build --release --target "$HOST"
# iOS device + simulator: staticlib only (no cdylib/bin — avoids linking a dylib/CLI for iOS).
for T in "$IOS" "$SIM"; do
  cargo rustc --release --target "$T" --lib --crate-type staticlib
done

echo "== [2/5] generate Swift bindings (library mode) =="
rm -rf "$STAGE"; mkdir -p "$STAGE/gen" "$STAGE/headers"
cargo run --release --bin uniffi-bindgen -- \
  generate --library "$FFI/target/$HOST/release/$LIB.dylib" \
  --language swift --out-dir "$STAGE/gen"

echo "== [3/5] stage headers + module map =="
cp "$STAGE/gen/mls_ffiFFI.h" "$STAGE/headers/"
# XCFramework header modules must be named exactly `module.modulemap`.
cat > "$STAGE/headers/module.modulemap" <<'EOF'
module mls_ffiFFI {
    header "mls_ffiFFI.h"
    export *
}
EOF

echo "== [4/5] assemble XCFramework =="
if [ "$CHECK_ONLY" != "--check" ]; then
  rm -rf "$XCF"
  xcodebuild -create-xcframework \
    -library "$FFI/target/$HOST/release/$LIB.a" -headers "$STAGE/headers" \
    -library "$FFI/target/$IOS/release/$LIB.a"  -headers "$STAGE/headers" \
    -library "$FFI/target/$SIM/release/$LIB.a"  -headers "$STAGE/headers" \
    -output "$XCF" >/dev/null
fi

echo "== [5/5] place bindings + write manifest =="
mkdir -p "$BINDINGS_DIR"
NEW_SWIFT="$STAGE/gen/mls_ffi.swift"
# Stale-binding check: committed bindings must match freshly generated ones.
if [ "$CHECK_ONLY" = "--check" ]; then
  if ! diff -q "$NEW_SWIFT" "$BINDINGS_DIR/mls_ffi.swift" >/dev/null 2>&1; then
    echo "ERROR: committed Swift bindings are stale. Re-run scripts/build_mls_ffi.sh and commit." >&2
    exit 1
  fi
  echo "bindings up to date."
  exit 0
fi
cp "$NEW_SWIFT" "$BINDINGS_DIR/mls_ffi.swift"

MANIFEST="$PKG/ARTIFACTS.md"
{
  echo "# MlsFfi build artifacts (generated by scripts/build_mls_ffi.sh)"
  echo
  echo "- Date: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "- UniFFI: 0.29 · Rust: $(rustc --version | awk '{print $2}') · Xcode: $(xcodebuild -version | head -1 | awk '{print $2}')"
  echo "- Deployment targets: macOS $MACOSX_DEPLOYMENT_TARGET, iOS $IPHONEOS_DEPLOYMENT_TARGET"
  echo
  echo "## Slices (arch → static lib SHA-256)"
  for pair in "$HOST" "$IOS" "$SIM"; do
    f="$FFI/target/$pair/release/$LIB.a"
    printf -- "- %s → %s\n" "$pair" "$(shasum -a 256 "$f" | awk '{print $1}')"
  done
  echo
  echo "## Bindings"
  printf -- "- mls_ffi.swift → %s\n" "$(shasum -a 256 "$BINDINGS_DIR/mls_ffi.swift" | awk '{print $1}')"
  echo
  echo "## XCFramework slices"
  ls "$XCF" 2>/dev/null | sed 's/^/- /' || true
} > "$MANIFEST"

echo "done. XCFramework: $XCF"
